language: node_js
node_js:
  - "6"
  - "4"
jdk:
    - oraclejdk8

before_install:
    # install Neo4j locally:
    - java -version
    - wget http://dist.neo4j.org/neo4j-community-3.0.3-unix.tar.gz
    - tar -xzf neo4j-community-3.0.3-unix.tar.gz
    - neo4j-community-3.0.3/bin/neo4j start
